Repository mattermost/mattermost-plugin-solar-lottery, pull requests merged in 2020-04, with the labels that each got.

#26 Define maintainer
  CODEOWNERS
  README.md
Labels: 3: Reviews Complete

#25 Add /lotto shift leave command
  server/command/info.go
  server/command/shift.go
  server/command/shift_leave.go
  server/solarlottery/shift_join_leave.go
  server/solarlottery/user.go
  server/solarlottery/user_messages.go
Labels: 2: QA Review

#30 Drop webapp folder
  plugin.json
  webapp/.babelrc
  webapp/.eslintrc.json
  webapp/.gitignore
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/index.js
  webapp/src/manifest.js
  webapp/src/manifest.test.js
  webapp/tsconfig.json
  webapp/webpack.config.js
Labels: 3: Reviews Complete

#31 Drop second maintainer from CODEOWNERS
  CODEOWNERS
Labels: 2: Dev Review
